name: dienos_darbai
description: "Darbuotojų ataskaitų registravimo sistema"
version: 1.0.0+1
environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  pdf: ^3.10.4
  shared_preferences: ^2.2.2
  pdf_image_renderer: ^1.0.1
  permission_handler: ^11.0.0
  open_file: ^3.3.2
  image_picker: ^1.0.7
  printing: ^5.12.0
  image: ^4.1.3
  intl: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.14.3
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/logo_nasta.png
    - assets/images/background.jpg
  uses-material-design: true  # Teisingas formatas
